### ISSUE TITLE
where the folder blender should be put in

### ISSUE THREAD

**Issue by PKUFlyingPig** [jonepatr/genea_visualizer#5]
I found that the docker file will download a file and uncompressed it ( blender ). Due to the internet, it downloaded quite slowly, so I download it manually, but I don't know where should I put the folder in. I found that in the docker file, it made the blender directory in the root folder, but I don't have the permission on my lab machine, so I put it in my home directory. So is it ok to do so ? If it is ok ,and where should I modify to make it work. If I put the blender in /home/abc, what's the server_url should I use ?

**Comment by jonepatr** [comment]
I would recommend you to put the unpacked blender folder into the `celery-queue` folder (so that the name for example is `blender-2.83.0-linux64`), and then remove line 9 from the Dockerfile (https://github.com/jonepatr/genea_visualizer/blob/master/celery-queue/Dockerfile#L9). Then you want to edit line 81 in `tasks.py` (https://github.com/jonepatr/genea_visualizer/blob/master/celery-queue/tasks.py#L81), and probably just have it as `"/queue/blender-2.83.0-linux64/blender"`. Haven't tested this, but it should work.
