### ISSUE TITLE
come from speech-driven-hand-gesture-generation

### ISSUE THREAD

**Issue by guofengming11-chinese** [jonepatr/genea_visualizer#9]
Sorry to disturb again, i m very interested in your achievement .
 In speech-driven-hand-gesture-generation i get txt file. Could i change the txt file into the video just like the one below, using this project?  And maybe in this project i can only change bvh file into the one below?
Thanks!
![image](https://user-images.githubusercontent.com/67827587/116049504-edd7ee00-a6a8-11eb-8f21-a1e6f53822fa.png)

**Comment by Svito-zar** [comment]
This repository lets you animate BVH files on such an avatar.
It takes the BVH file as input and generates video animation as output.
It can only work with the BVH file format

**Comment by guofengming11-chinese** [comment]
is that means there's  no way to change the txt file to video animation?  It can only change into the video of skeleton？

**Comment by Svito-zar** [comment]
yeah, there is no simple way to convert .txt file into a BVH file, because the `.txt` file you have contains 3D coordinates, instead of 3D joint angles.

But we have a few other more recent systems which can generate motion in the BVH format:
https://github.com/Svito-zar/gesticulator
https://github.com/simonalexanderson/StyleGestures
